{"uuid": "6c75fabb-3fda-4058-b3f5-eb49b0eb920c", "children": ["c1572eba-6fca-4b65-a344-81f28855dfce"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/anastasiiamonakhova/otus/selenium_tests_with_dockerfile/tests/logs/test_login_window.log'\n", "trace": "  File \"/Users/anastasiiamonakhova/otus/seleium-tests-with-jenkins/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anastasiiamonakhova/otus/seleium-tests-with-jenkins/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anastasiiamonakhova/otus/seleium-tests-with-jenkins/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/anastasiiamonakhova/otus/selenium_tests_with_dockerfile/conftest.py\", line 27, in browser\n    file_handler = logging.FileHandler(f\"logs/{request.node.name}.log\")\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1181, in __init__\n    StreamHandler.__init__(self, self._open())\n                                 ^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1213, in _open\n    return open_func(self.baseFilename, self.mode,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1678395539771, "stop": 1678395539771}], "start": 1678395539771, "stop": 1678395539847}